#!/usr/bin/env bash
printf '%s\n' 'Archived experimental comparison; PTv3/Sonata are unimplemented MLP placeholders. See docs/EXPERIMENTAL_POINT_ENCODERS.md.' >&2
exit 1
# DP3 点云编码器对比 - 快速参考

echo "=========================================="
echo "  DP3 点云编码器对比 - Sonata vs PTv3 vs PointNet"
echo "=========================================="
echo ""

echo "📊 架构对比"
echo "----------------------------------------"
echo ""
echo "1️⃣  PointNet (基线 - 60k 训练):"
echo "  输入: (B, 2048, 3)"
echo "  MLP: 3→64→128→256"
echo "  Pool: (B, 256)"
echo "  参数: 67K 可训练"
echo "  预训练: ❌"
echo ""
echo "2️⃣  PTv3 (CVPR 2024 - 50k 训练):"
echo "  输入: (B, 2048, 3)"
echo "  Encoder: 64→128→256→512 (4 stages)"
echo "  Per-point: (B, 2048, 512)"
echo "  Pool: (B, 512)"
echo "  Projection: 512→256"
echo "  参数: 46M 冻结 + 131K 可训练"
echo "  预训练: ✅"
echo ""
echo "3️⃣  Sonata (CVPR 2025 Highlight - 50k 训练):"
echo "  输入: (B, 2048, 3)"
echo "  Encoder: 48→96→192→384→512 (5 stages)"
echo "  Block depths: [3,3,3,12,3]"
echo "  Per-point: (B, 2048, 512)"
echo "  Pool: (B, 512)"
echo "  Projection: 512→256"
echo "  参数: 108.5M 冻结 + 131K 可训练"
echo "  预训练: ✅ Self-supervised"
echo ""

echo "🏆 性能对比"
echo "----------------------------------------"
echo "参数量:"
echo "  PointNet: 67K"
echo "  PTv3:     46M     (685× PointNet)"
echo "  Sonata:   108.5M  (1,619× PointNet, 2.36× PTv3)"
echo ""
echo "权重大小:"
echo "  PointNet: < 1 MB"
echo "  PTv3:     ~180 MB"
echo "  Sonata:   ~434 MB"
echo ""
echo "架构深度:"
echo "  PointNet: 3 layers"
echo "  PTv3:     4 stages, 12 blocks total"
echo "  Sonata:   5 stages, 24 blocks total (Stage 4: 12 blocks)"
echo ""
echo "预训练方式:"
echo "  PointNet: 无"
echo "  PTv3:     有监督预训练"
echo "  Sonata:   Self-supervised (72.5% ScanNet 线性探测)"
echo ""

echo "🚀 启动训练"
echo "----------------------------------------"
echo "PointNet (基线):"
echo "  python scripts/train_dp3_compare.py --encoder pointnet --steps 60000"
echo ""
echo "PTv3 (CVPR 2024 Oral):"
echo "  python scripts/train_dp3_compare.py --encoder ptv3 --steps 50000"
echo "  # 可选: --ptv3-weights /path/to/ptv3.pth"
echo ""
echo "Sonata (CVPR 2025 Highlight) - 推荐:"
echo "  python scripts/train_dp3_compare.py --encoder sonata --steps 50000"
echo "  # 可选: --sonata-weights /path/to/sonata.pth"
echo ""

echo "📥 获取预训练权重"
echo "----------------------------------------"
echo "PTv3:"
echo "  GitHub: https://github.com/Pointcept/PointTransformerV3"
echo "  HF:     https://huggingface.co/jayakumarpujar/Ptv3"
echo ""
echo "Sonata (推荐):"
echo "  GitHub: https://github.com/facebookresearch/sonata"
echo "  权重:   sonata.pth (~434 MB)"
echo ""

echo "💡 推荐选择"
echo "----------------------------------------"
echo "🥇 Sonata  - 最强性能，CVPR 2025 Highlight"
echo "🥈 PTv3    - 平衡性能与效率，CVPR 2024 Oral"
echo "🥉 PointNet - 轻量快速，适合快速原型"
echo ""

echo "⚙️  配置对比"
echo "----------------------------------------"
echo "Sonata:"
echo "  --policy.use_sonata_encoder=true"
echo "  --policy.sonata_feature_dim=512"
echo "  --policy.sonata_model_path=/path/to/sonata.pth"
echo ""
echo "PTv3:"
echo "  --policy.use_ptv3_encoder=true"
echo "  --policy.ptv3_feature_dim=512"
echo "  --policy.ptv3_model_path=/path/to/ptv3.pth"
echo ""
echo "PointNet:"
echo "  # 默认，无需额外配置"
echo ""

echo "📁 核心文件"
echo "----------------------------------------"
echo "  src/lerobot/policies/dp3/"
echo "    ├── sonata_encoder.py         # Sonata 实现"
echo "    ├── ptv3_encoder.py           # PTv3 实现"
echo "    ├── modeling_dp3.py           # 统一接口"
echo "    └── configuration_dp3.py      # 配置"
echo ""
echo "  scripts/train_dp3_compare.py    # 训练脚本"
echo "  docs/SONATA_ENCODER_GUIDE.md    # Sonata 文档"
echo ""

echo "=========================================="
echo "推荐: 使用 Sonata 获得最佳性能！🚀"
echo "=========================================="
