#!/usr/bin/env bash
printf '%s\n' 'Archived experimental reference; PTv3 is an unimplemented MLP placeholder. See docs/EXPERIMENTAL_POINT_ENCODERS.md.' >&2
exit 1
# PTv3 编码器集成 - 快速参考卡

echo "=========================================="
echo "  DP3 PTv3 Encoder - 快速参考"
echo "=========================================="
echo ""

echo "📊 架构对比"
echo "----------------------------------------"
echo "PointNet (基线):"
echo "  输入: (B, 2048, 3)"
echo "  MLP: 3→64→128→256"
echo "  Pool: (B, 256)"
echo "  参数: 67K 可训练"
echo "  训练: 60k steps"
echo ""
echo "PTv3 Encoder (新):"
echo "  输入: (B, 2048, 3)"
echo "  Encoder: 64→128→256→512 (bottleneck)"
echo "  Per-point: (B, 2048, 512)"
echo "  Pool: (B, 512)"
echo "  Projection: 512→256"
echo "  输出: (B, 256)"
echo "  参数: 46M 冻结 + 131K 可训练"
echo "  训练: 50k steps"
echo ""

echo "🔑 关键参数"
echo "----------------------------------------"
echo "  use_ptv3_encoder = true"
echo "  ptv3_feature_dim = 512          # Encoder bottleneck"
echo "  ptv3_freeze_backbone = true"
echo "  point_cloud_encoder_output_dim = 256"
echo "  point_cloud_use_projection = true"
echo ""

echo "🚀 启动训练"
echo "----------------------------------------"
echo "方法 1 (推荐):"
echo "  python scripts/train_dp3_compare.py --encoder ptv3 --steps 50000"
echo ""
echo "方法 2:"
echo "  ./outputs/franka_duo_dp3_action20_pc_only_dit768_ptv3_il_50k/run_train.sh"
echo ""

echo "⚠️  重要提示"
echo "----------------------------------------"
echo "  - 当前使用占位符模型（随机初始化）"
echo "  - 需要真实 PTv3 权重以获得最佳效果"
echo "  - 下载: https://github.com/Pointcept/PointTransformerV3"
echo "  - 或: https://huggingface.co/jayakumarpujar/Ptv3"
echo ""

echo "📁 核心文件"
echo "----------------------------------------"
echo "  src/lerobot/policies/dp3/"
echo "    ├── ptv3_encoder.py           # PTv3 编码器实现"
echo "    ├── configuration_dp3.py      # 配置（已修改）"
echo "    └── modeling_dp3.py           # 模型（已修改）"
echo ""
echo "  scripts/train_dp3_compare.py    # 训练脚本"
echo "  PTv3_FINAL_IMPLEMENTATION.md    # 完整文档"
echo ""

echo "🧪 快速测试"
echo "----------------------------------------"
echo "  # 测试导入"
echo "  uv run python -c 'from lerobot.policies.dp3.ptv3_encoder import PTv3Encoder; print(\"✅\")'"
echo ""
echo "  # 干运行"
echo "  python scripts/train_dp3_compare.py --encoder ptv3 --dry-run"
echo ""

echo "=========================================="
echo "准备就绪！现在可以开始训练 🎉"
echo "=========================================="
