bddl_files: /home/droid/project/LIBERO/libero/libero/bddl_files
init_states: /home/droid/project/LIBERO/libero/libero/init_files
datasets: /data/lerobot-imf-attnres-exp/datasets
assets: /home/droid/project/LIBERO/libero/libero/assets
